// <auto-generated />
namespace Blog.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_writer_about : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_writer_about));
        
        string IMigrationMetadata.Id
        {
            get { return "202311051324391_add_writer_about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
