// <auto-generated />
namespace Blog.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addstatusproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstatusproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202311071726045_add-status-property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
