// <auto-generated />
namespace Blog.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_HeadingTitle_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_HeadingTitle_length));
        
        string IMigrationMetadata.Id
        {
            get { return "202311242309430_update_HeadingTitle_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
